### ISSUE TITLE
Cache modules

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-require-module#3]
@rwjblue what do you think about caching the modules that have been required?

```js
let CACHE = {};

requireModule(module, exportName = 'default', cache = true) {
  let cacheKey = `${module}|${exportName}`;
  
  if (CACHE[cacheKey] && cache) {
    return CACHE[cacheKey];
  } else {
   // blah blah blah...
  }
}
```

**Comment by rwjblue** [comment]
The underlying loader caches them so that they are only evaluated once.

Take a look at [this test](https://github.com/ember-cli/loader.js/blob/master/tests/all.js#L64-L120)

**Comment by offirgolan** [comment]
Ah nice! I was curious as to how much overhead it would add to continuously require modules but if the underlying loader caches it already then there is nothing I need to do 😛. Thanks @rwjblue!
